apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=      # Base64 encoded value of 'admin'
  password: cmFqZXNoY2VudG9z  # Base64 encoded value of 'rajeshcentos'
